apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.backend.port }}
      targetPort: 8080
  type: {{ .Values.service.backend.type }}