apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.react.port }}
      targetPort: 80
  type: {{ .Values.service.react.type }}